# Generated by Django 4.2.2 on 2023-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdata",
            name="time_created",
            field=models.TimeField(auto_now=True),
        ),
    ]
