# Generated by Django 4.2.2 on 2023-08-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='blogdata',
            name='images',
        ),
        migrations.RemoveField(
            model_name='blogdata',
            name='time_created',
        ),
    ]
