# Generated by Django 4.2.2 on 2023-08-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_blogdata_desc_remove_blogdata_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='desc',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='time_created',
            field=models.TimeField(auto_now=True),
        ),
    ]
