# Generated by Django 4.2.2 on 2023-08-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogdata_desc_blogdata_image1_blogdata_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
