# Generated by Django 4.2.2 on 2023-08-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blogdata_image1_alter_blogdata_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
