apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2 # This will be overridden in specific environments
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: django-local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000