name: CD Pipeline - Deploy to EKS

on:
  workflow_run:
    workflows: ["CI Pipeline - Build Django App Container"]
    types:
      - completed
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: django-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy to EKS
        run: |
          helm upgrade --install django-app ./django \
            --namespace production \
            --create-namespace \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/django-app \
            --set image.tag=latest \
            --wait