name: CI Pipeline - Build Django App Container

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install Linter
          run: |
            python -m pip install --upgrade pip
            pip install flake8 black

        - name: Run Code Formatter Check
          run: |
            black --check blogs/

        - name: Run Linter
          run: |
            flake8 --max-line-length=100 blogs/

    format:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install Code Formatter
          run: |
            python -m pip install --upgrade pip
            pip install black

        - name: Format Code
          run: |
            black blogs/

    sast:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install Bandit
          run: |
            python -m pip install --upgrade pip
            pip install bandit

        - name: Run Bandit
          run: |
            bandit -r blogs/

    backend:
        runs-on: ubuntu-latest
        needs: [lint, sast]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
      
            - name: Build and push backend container
              uses: docker/build-push-action@v3
              with:
                context: blogs/
                file: blogs/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest
    test:
      runs-on: ubuntu-latest
      needs: backend
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install Test Dependencies
          run: |
            pip install coverage xmlrunner

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Docker Image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:latest blogs/

        - name: Run Unit Tests and Generate Report
          run: |
            docker run --rm -v ${{ github.workspace }}/test-reports:/app/test-reports ${{ secrets.DOCKER_USERNAME }}/django-app:latest sh -c "python manage.py test blogs --testrunner=xmlrunner.extra.djangotestrunner.XMLTestRunner --output-file /app/test-reports/test_results.xml"

        - name: Upload Test Results
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: test-reports/